[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  port = 8888
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[functions]
  node_bundler = "esbuild"